version: "3"
services:
  web: &rails_base
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
      - "9394:9394"
    depends_on:
      - db
    environment:
      RAILS_ENV: local_production
      SKYLIGHT_ENV: development
      SKYLIGHT_ENABLED: "true"
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      YARN_INTEGRITY_ENABLED: "false"
    volumes:
      - .:/usr/src/app
    command: bash -c "bundle exec rails server -b 0.0.0.0 -p 3000"
  jobs:
    ports: []
    <<: *rails_base
    command: rails jobs:work
  webpacker:
    ports: []
    <<: *rails_base
    command: ./bin/webpack-dev-server
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
